[11062025 22:15:17] modules /code/src/modules.c:197-message: new module lib/dionaea/curl.so 0x5632a8b17670 fn 0x7fe7c6c658d6
[11062025 22:15:17] curl /code/modules/curl/module.c:593-debug: curl_new
[11062025 22:15:17] curl /code/modules/curl/module.c:638-info: curl version 7.58.0 features:c-ares,idn,ipv6,largefile,ntlm,spnego,ssl,libz protocols:dict,file,ftp,ftps,gopher,http,https,imap,imaps,ldap,ldaps,pop3,pop3s,rtmp,rtsp,smb,smbs,smtp,smtps,telnet,tftp 
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.download.offer cb 0x7fe7c6c6570d ctx (nil)
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8b1d170 pattern dionaea.download.offer cb 0x7fe7c6c6570d ctx (nil)
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.upload.request cb 0x7fe7c6c6570d ctx (nil)
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8b1c520 pattern dionaea.upload.request cb 0x7fe7c6c6570d ctx (nil)
[11062025 22:15:17] modules /code/src/modules.c:197-message: new module lib/dionaea/python.so 0x5632a8b191c0 fn 0x7fe7c18b8868
[11062025 22:15:17] python /code/modules/python/module.c:324-debug: new /code/modules/python/module.c 0x5632a8abf810
[11062025 22:15:17] python /code/modules/python/module.c:328-debug: Python Interpreter /usr/bin/python3.6
[11062025 22:15:17] python /code/modules/python/module.c:366-debug: running sys.path.insert(0, 'lib/dionaea/python') default
[11062025 22:15:17] services /dionaea/services.py:114-info: Initializing services ...
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.blackhole
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.cmd
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.core
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.echo
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.emu
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.emu_scripts
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.exception
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.fail2ban
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ftp
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ftp_download
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.hpfeeds
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.http
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ihandlers
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log_db_sql
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log_incident
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.log_json
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.logsql
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.memcache
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mirror
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mongo
[11062025 22:15:17] asn1fields /dionaea/smb/include/asn1fields.py:156-debug: i2s {0: 'completed', 1: 'incomplete', 2: 'reject'}
[11062025 22:15:17] asn1fields /dionaea/smb/include/asn1fields.py:157-debug: s2i {'completed': 0, 'incomplete': 1, 'reject': 2}
[11062025 22:15:17] asn1fields /dionaea/smb/include/asn1fields.py:338-debug: self.choice {48: <class 'dionaea.smb.include.gssapifields.NegTokenInit'>}
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mqtt
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mssql
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.mysql
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.ndrlib
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.nfq
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.p0f
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.pptp
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.printer
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.s3
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.services
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.sip
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.smb
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.store
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.submit_http
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.submit_http_post
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.tftp
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.upnp
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.util
[11062025 22:15:17] dionaea /dionaea/__init__.py:148-info: Import module dionaea.virustotal
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:25-info: Load iHandlers
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.*.mkshell cb 0x7fe7c18b7890 ctx (nil)
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a90b9740 pattern dionaea.*.mkshell cb 0x7fe7c18b7890 ctx (nil)
[11062025 22:15:17] modules /code/src/modules.c:197-message: new module lib/dionaea/emu.so 0x5632a8b19f10 fn 0x7fe7c0bcac19
[11062025 22:15:17] emu /code/modules/emu/module.c:37-debug: emu_new
[11062025 22:15:17] dionaea /code/src/dionaea.c:669-debug: Creating processors tree
[11062025 22:15:17] processor /code/src/processor.c:25-debug: processors_tree_create - processor: filter_streamdumper
[11062025 22:15:17] processor /code/src/processor.c:707-debug: Key file does not have key “config.allow.0.protocols” in group “processor.filter_streamdumper”
[11062025 22:15:17] processor /code/src/processor.c:744-debug: Key file does not have key “config.deny.0.types” in group “processor.filter_streamdumper”
[11062025 22:15:17] processor /code/src/processor.c:629-debug: Dumping filter rules ...
[11062025 22:15:17] processor /code/src/processor.c:638-debug: allow:
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - protocol  
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - type  
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - accept
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - protocol  
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - ftpctrl
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - type  
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - connect
[11062025 22:15:17] processor /code/src/processor.c:638-debug: deny:
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - protocol  
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - ftpdata
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - ftpdatacon
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - xmppclient
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - type  
[11062025 22:15:17] processor /code/src/processor.c:25-debug: processors_tree_create - processor: streamdumper
[11062025 22:15:17] processor /code/src/processor.c:339-info: var/lib/dionaea/bistreams/2025-06-11/ <-> var/lib/dionaea/bistreams/%Y-%m-%d/
[11062025 22:15:17] dionaea /code/src/dionaea.c:676-debug: processo: filter_streamdumper
[11062025 22:15:17] processor /code/src/processor.c:25-debug: processors_tree_create - processor: filter_emu
[11062025 22:15:17] processor /code/src/processor.c:718-debug: Key file does not have key “config.allow.0.types” in group “processor.filter_emu”
[11062025 22:15:17] processor /code/src/processor.c:629-debug: Dumping filter rules ...
[11062025 22:15:17] processor /code/src/processor.c:638-debug: allow:
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - protocol  
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - smbd
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - epmapper
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - nfqmirrord
[11062025 22:15:17] processor /code/src/processor.c:654-debug:   - mssqld
[11062025 22:15:17] processor /code/src/processor.c:645-debug: - type  
[11062025 22:15:17] processor /code/src/processor.c:25-debug: processors_tree_create - processor: emu
[11062025 22:15:17] emu /code/modules/emu/detect.c:39-debug: proc_emu_ctx_cfg_new node
[11062025 22:15:17] emu /code/modules/emu/detect.c:86-debug:  files 3 filesize 524288 sockets 3 steps 1073741824 idle 30.000000 listen 30.000000 sustain 120.000000 cpu 120.000000 
[11062025 22:15:17] dionaea /code/src/dionaea.c:676-debug: processo: filter_emu
[11062025 22:15:17] processor /code/src/processor.c:71-debug:      filter
[11062025 22:15:17] processor /code/src/processor.c:71-debug:          streamdumper
[11062025 22:15:17] processor /code/src/processor.c:71-debug:      filter
[11062025 22:15:17] processor /code/src/processor.c:71-debug:          emu
[11062025 22:15:17] dionaea /code/src/dionaea.c:726-debug: old umask -----w--w-
[11062025 22:15:17] dionaea /code/src/dionaea.c:727-debug: new umask -----w--w-
[11062025 22:15:17] dionaea /code/src/dionaea.c:742-info: Using 1048576 as limit for fds
[11062025 22:15:17] modules /code/src/modules.c:184-message: start module 0x5632a8b17670
[11062025 22:15:17] modules /code/src/modules.c:184-message: start module 0x5632a8b191c0
[11062025 22:15:17] python /code/modules/python/module.c:293-info: start /code/modules/python/module.c
[11062025 22:15:17] python /code/modules/python/module.c:303-info: start dionaea.log 0x5632a8b0e7b0 0x7fe7c0636ae8
[11062025 22:15:17] python /code/modules/python/module.c:303-info: start dionaea.services 0x5632a8b0ecf0 0x7fe7c0636cc8
[11062025 22:15:17] services /dionaea/services.py:164-info: Starting services ...
[11062025 22:15:17] services /dionaea/services.py:32-info: Starting services on interface eth0 ...
[11062025 22:15:17] services /dionaea/services.py:34-info: Bind interfaces to address '172.19.0.4' ...
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a8db0fe0 addr 172.19.0.4 port 1883 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a8db0fe0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a8db0fe0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 9 172.19.0.4:1883
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:1883'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b13050
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b13050 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a8db0fe0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a8db1770 addr 172.19.0.4 port 42 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a8db1770 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a8db1770
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 10 172.19.0.4:42
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:42'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b13450
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b13450 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a8db1770
[11062025 22:15:17] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7fe7bd5f7b40> __init__
[11062025 22:15:17] sip /dionaea/sip/__init__.py:575-info: SIP Session created with personality 'default'
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90b9770 addr 172.19.0.4 port 5060 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90b9770 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90b9770
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 13 172.19.0.4:5060
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:5060'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8e7ee80
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8e7ee80 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90b9770
[11062025 22:15:17] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7fe7bd5f74c8> __init__
[11062025 22:15:17] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[11062025 22:15:17] ftp /dionaea/ftp.py:167-debug: ftp test
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90eb750 addr 172.19.0.4 port 21 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90eb750 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90eb750
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 17 172.19.0.4:21
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:21'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b08cb0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b08cb0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90eb750
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90d3f70 addr 172.19.0.4 port 1433 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90d3f70 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90d3f70
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 18 172.19.0.4:1433
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:1433'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afa820
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afa820 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90d3f70
[11062025 22:15:17] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90d4970 addr 172.19.0.4 port 1723 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90d4970 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90d4970
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 19 172.19.0.4:1723
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:1723'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b13bd0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b13bd0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90d4970
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90d5ea0 addr 172.19.0.4 port 445 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90d5ea0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90d5ea0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 20 172.19.0.4:445
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:445'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afa520
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afa520 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90d5ea0
[11062025 22:15:17] memcache /dionaea/memcache/__init__.py:45-debug: start memcache
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90d6c50 addr 172.19.0.4 port 11211 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90d6c50 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90d6c50
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 21 172.19.0.4:11211
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:11211'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b07340
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b07340 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90d6c50
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90d8340 addr 172.19.0.4 port 9100 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90d8340 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90d8340
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 22 172.19.0.4:9100
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:9100'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b07980
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b07980 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90d8340
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a8f907e0 addr 172.19.0.4 port 135 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a8f907e0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a8f907e0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 23 172.19.0.4:135
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:135'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afc640
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afc640 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a8f907e0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a8f90f70 addr 172.19.0.4 port 69 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a8f90f70
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 24 172.19.0.4:69
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '172.19.0.4' node '172.19.0.4:69'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90df060 addr 172.19.0.4 port 27017 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90df060 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90df060
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 25 172.19.0.4:27017
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:27017'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afcb80
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afcb80 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90df060
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90df7f0 addr 172.19.0.4 port 1900 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90df7f0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 26 172.19.0.4:1900
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '172.19.0.4' node '172.19.0.4:1900'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90df7f0 len 20
[11062025 22:15:17] http /dionaea/http.py:232-debug: http test
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90dff80 addr 172.19.0.4 port 80 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90dff80 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90dff80
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 27 172.19.0.4:80
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:80'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afd240
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afd240 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90dff80
[11062025 22:15:17] http /dionaea/http.py:232-debug: http test
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a8d530e0 addr 172.19.0.4 port 443 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a8d530e0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a8d530e0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 28 172.19.0.4:443
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:443'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection_tls.c:158-debug: connection_tls_mkcert con 0x5632a8d530e0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90e4320 addr 172.19.0.4 port 3306 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90e4320 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90e4320
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 29 172.19.0.4:3306
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:3306'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b04140
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b04140 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90e4320
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90e0b70 addr 172.19.0.4 port 23 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90e0b70 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90e0b70
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 30 172.19.0.4:23
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:23'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b047a0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b047a0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90e0b70
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90e2390 addr 172.19.0.4 port 53 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90e2390
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 31 172.19.0.4:53
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '172.19.0.4' node '172.19.0.4:53'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90e2390 len 20
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90e2b20 addr 172.19.0.4 port 53 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90e2b20 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90e2b20
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 32 172.19.0.4:53
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '172.19.0.4' node '172.19.0.4:53'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b04f40
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b04f40 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90e2b20
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90f4680 addr 172.19.0.4 port 123 iface eth0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90f4680
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 33 172.19.0.4:123
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '172.19.0.4' node '172.19.0.4:123'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90f4680 len 20
[11062025 22:15:17] services /dionaea/services.py:32-info: Starting services on interface lo ...
[11062025 22:15:17] services /dionaea/services.py:34-info: Bind interfaces to address '127.0.0.1' ...
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90f4e10 addr 127.0.0.1 port 1883 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90f4e10 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90f4e10
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 34 127.0.0.1:1883
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:1883'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b05500
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b05500 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90f4e10
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90f55a0 addr 127.0.0.1 port 42 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90f55a0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90f55a0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 35 127.0.0.1:42
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:42'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b05ad0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b05ad0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90f55a0
[11062025 22:15:17] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7fe7bd570558> __init__
[11062025 22:15:17] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[11062025 22:15:17] ftp /dionaea/ftp.py:167-debug: ftp test
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90f64c0 addr 127.0.0.1 port 21 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90f64c0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90f64c0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 36 127.0.0.1:21
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:21'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0da10
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0da10 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90f64c0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a90f6c50 addr 127.0.0.1 port 1433 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a90f6c50 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a90f6c50
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 37 127.0.0.1:1433
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:1433'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b03a80
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b03a80 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a90f6c50
[11062025 22:15:17] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a910e330 addr 127.0.0.1 port 1723 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a910e330 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a910e330
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 38 127.0.0.1:1723
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:1723'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b030a0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b030a0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a910e330
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a910eac0 addr 127.0.0.1 port 445 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a910eac0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a910eac0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 39 127.0.0.1:445
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:445'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b02ce0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b02ce0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a910eac0
[11062025 22:15:17] memcache /dionaea/memcache/__init__.py:45-debug: start memcache
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a910f250 addr 127.0.0.1 port 11211 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a910f250 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a910f250
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 40 127.0.0.1:11211
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:11211'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0a250
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0a250 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a910f250
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a910f9e0 addr 127.0.0.1 port 9100 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a910f9e0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a910f9e0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 41 127.0.0.1:9100
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:9100'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b06660
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b06660 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a910f9e0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9110e80 addr 127.0.0.1 port 135 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9110e80 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9110e80
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 42 127.0.0.1:135
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:135'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b03460
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b03460 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9110e80
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9111610 addr 127.0.0.1 port 69 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9111610
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 43 127.0.0.1:69
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:69'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9111da0 addr 127.0.0.1 port 27017 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9111da0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9111da0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 44 127.0.0.1:27017
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:27017'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0d0d0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0d0d0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9111da0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9112530 addr 127.0.0.1 port 1900 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9112530
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 45 127.0.0.1:1900
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:1900'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9112530 len 20
[11062025 22:15:17] http /dionaea/http.py:232-debug: http test
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9112cc0 addr 127.0.0.1 port 80 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9112cc0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9112cc0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 46 127.0.0.1:80
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:80'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afca00
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afca00 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9112cc0
[11062025 22:15:17] http /dionaea/http.py:232-debug: http test
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9113450 addr 127.0.0.1 port 443 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9113450 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9113450
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 47 127.0.0.1:443
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:443'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection_tls.c:158-debug: connection_tls_mkcert con 0x5632a9113450
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a91222c0 addr 127.0.0.1 port 3306 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a91222c0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a91222c0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 48 127.0.0.1:3306
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:3306'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8fb3ff0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8fb3ff0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a91222c0
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9122a50 addr 127.0.0.1 port 23 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9122a50 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9122a50
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 49 127.0.0.1:23
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:23'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8dbef70
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8dbef70 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9122a50
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9113be0 addr 127.0.0.1 port 53 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9113be0
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 50 127.0.0.1:53
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:53'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9113be0 len 20
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9114370 addr 127.0.0.1 port 53 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9114370 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9114370
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 51 127.0.0.1:53
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '127.0.0.1' node '127.0.0.1:53'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8f9d7f0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8f9d7f0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9114370
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9114b00 addr 127.0.0.1 port 123 iface lo
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9114b00
[11062025 22:15:17] util /code/src/util.c:185-debug: Key file does not have key “listen.use_ipv4_mapped_ipv6” in group “dionaea”
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 52 127.0.0.1:123
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '127.0.0.1' node '127.0.0.1:123'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9114b00 len 20
[11062025 22:15:17] services /dionaea/services.py:34-info: Bind interfaces to address '::1' ...
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9115290 addr ::1 port 1883 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9115290 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9115290
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 53 ::1:1883
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:1883'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8ff52c0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8ff52c0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9115290
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9115a20 addr ::1 port 42 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9115a20 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9115a20
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 54 ::1:42
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:42'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8c20370
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8c20370 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9115a20
[11062025 22:15:17] sip /dionaea/sip/__init__.py:568-debug: <dionaea.sip.SipSession object at 0x7fe7bd581750> __init__
[11062025 22:15:17] services /dionaea/services.py:46-warning: Unable to start service
Traceback (most recent call last):
  File "lib/dionaea/python/dionaea/services.py", line 44, in start
    daemons = service.start(addr, iface=iface, config=srv.get("config", {}))
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 70, in start
    daemon = SipSession(proto=proto, config=config)
  File "lib/dionaea/python/dionaea/sip/__init__.py", line 571, in __init__
    self.config = SipConfig(config=config)
  File "lib/dionaea/python/dionaea/sip/extras.py", line 99, in __init__
    self._cur.execute("CREATE TABLE IF NOT EXISTS sdp (name STRING, sdp STRING)")
sqlite3.OperationalError: database is locked
[11062025 22:15:17] ftp /dionaea/ftp.py:167-debug: ftp test
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9116940 addr ::1 port 21 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9116940 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9116940
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 55 ::1:21
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:21'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b092f0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b092f0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9116940
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a91170d0 addr ::1 port 1433 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a91170d0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a91170d0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 56 ::1:1433
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:1433'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0db90
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0db90 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a91170d0
[11062025 22:15:17] pptp /dionaea/pptp/pptp.py:52-warning: No config provided. Using default values
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9117860 addr ::1 port 1723 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9117860 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9117860
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 57 ::1:1723
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:1723'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0c350
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0c350 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9117860
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9117ff0 addr ::1 port 445 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9117ff0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9117ff0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 58 ::1:445
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:445'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0cdd0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0cdd0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9117ff0
[11062025 22:15:17] memcache /dionaea/memcache/__init__.py:45-debug: start memcache
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9118780 addr ::1 port 11211 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9118780 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9118780
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 59 ::1:11211
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:11211'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0bd50
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0bd50 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9118780
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a912d730 addr ::1 port 9100 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a912d730 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a912d730
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 60 ::1:9100
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:9100'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b0cf50
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b0cf50 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a912d730
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a912ebd0 addr ::1 port 135 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a912ebd0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a912ebd0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 61 ::1:135
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:135'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b13bd0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b13bd0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a912ebd0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a912f360 addr ::1 port 69 iface lo
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a912f360
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 62 ::1:69
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:69'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a912faf0 addr ::1 port 27017 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a912faf0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a912faf0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 63 ::1:27017
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:27017'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b07a40
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b07a40 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a912faf0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9130280 addr ::1 port 1900 iface lo
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9130280
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 64 ::1:1900
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:1900'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9130280 len 20
[11062025 22:15:17] http /dionaea/http.py:232-debug: http test
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9130a10 addr ::1 port 80 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9130a10 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9130a10
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 65 ::1:80
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:80'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8afcb80
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8afcb80 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9130a10
[11062025 22:15:17] http /dionaea/http.py:232-debug: http test
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', '{content_type}'), ('Content-Length', '{content_length}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Content-Type', 'text/html; charset=utf-8'), ('Content-Length', '{content_length}'), ('Connection', '{connection}'), ('X-Powered-By', 'PHP/5.5.9-1ubuntu4.5')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Location', '{location}'), ('Connection', '{connection}')])
[11062025 22:15:17] http /dionaea/http.py:168-debug: Headers: OrderedDict([('Server', 'nginx'), ('Allow', '{allow}'), ('Connection', '{connection}')])
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a91311a0 addr ::1 port 443 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a91311a0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a91311a0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 66 ::1:443
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:443'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection_tls.c:158-debug: connection_tls_mkcert con 0x5632a91311a0
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9140010 addr ::1 port 3306 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9140010 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9140010
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 67 ::1:3306
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:3306'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b00700
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b00700 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a9140010
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a91407a0 addr ::1 port 23 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a91407a0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a91407a0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 68 ::1:23
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:23'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b09170
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b09170 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a91407a0
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9140f30 addr ::1 port 53 iface lo
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9140f30
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 69 ::1:53
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:53'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9140f30 len 20
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a91416c0 addr ::1 port 53 iface lo
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a91416c0 len 20
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a91416c0
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 70 ::1:53
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:208-debug: ip '::1' node '[::1]:53'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] incident /code/src/incident.c:376-debug: reporting 0x5632a8b033a0
[11062025 22:15:17] incident /code/src/incident.c:365-debug: incident 0x5632a8b033a0 dionaea.connection.tcp.listen
[11062025 22:15:17] incident /code/src/incident.c:160-debug: 	con: (ptr) 0x5632a91416c0
[11062025 22:15:17] blackhole /dionaea/blackhole.py:61-debug: start blackhole
[11062025 22:15:17] connection /code/src/connection.c:249-debug: connection_bind con 0x5632a9131930 addr ::1 port 123 iface lo
[11062025 22:15:17] connection /code/src/connection.c:169-debug: bind_local con 0x5632a9131930
[11062025 22:15:17] connection /code/src/connection.c:185-debug: bind_local socket 71 ::1:123
[11062025 22:15:17] pchild /code/src/pchild.c:180-debug: sending msg to child to bind port ...
[11062025 22:15:17] pchild /code/src/pchild.c:199-debug: child could bind the socket!
[11062025 22:15:17] connection /code/src/connection.c:297-debug: ip '::1' node '[::1]:123'
[11062025 22:15:17] connection /code/src/connection.c:744-debug: connection_set_nonblocking
[11062025 22:15:17] connection /code/src/connection.c:365-debug: connection_listen con 0x5632a9131930 len 20
[11062025 22:15:17] python /code/modules/python/module.c:303-info: start dionaea.ihandlers 0x5632a8b0f490 0x7fe7bef16c78
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:36-info: START THE IHANDLERS
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:29-debug: logsqlhandler ready!
[11062025 22:15:17] store /dionaea/store.py:32-debug: storehandler ready!
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.download.complete cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4548
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8b6fcb0 pattern dionaea.download.complete cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4548
[11062025 22:15:17] emu /dionaea/emu.py:28-debug: emuprofilehandler ready!
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.module.emu.profile cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4688
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8dfb5e0 pattern dionaea.module.emu.profile cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4688
[11062025 22:15:17] cmd /dionaea/cmd.py:389-debug: cmdshellhandler ready!
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.service.shell.* cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4708
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8e73820 pattern dionaea.service.shell.* cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4708
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern dionaea.download.offer cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4788
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8fe1040 pattern dionaea.download.offer cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4788
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.logsql.logsqlhandler object at 0x7fe7bd5a4508>
[11062025 22:15:17] incident /code/src/incident.c:165-debug: ihandler_new pattern * cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4508
[11062025 22:15:17] incident /code/src/incident.c:167-debug: ihandler 0x5632a8f10000 pattern * cb 0x7fe7c18ba8ce ctx 0x7fe7bd5a4508
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:144-info: Getting RPC Services
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:165-info: Setting RPC ServiceOps
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:184-debug: Trying to update table: dcerpcserviceops
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:192-info: ... not required
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:210-debug: Trying to update table: emu_services
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:217-debug: ... not required
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:259-debug: Trying to update table: downloads
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:266-debug: ... not required
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:424-info: Setting MySQL Command Ops
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:578-debug: Updating Table dcerpcs
[11062025 22:15:17] log_sqlite /dionaea/logsql.py:589-debug: ... not required
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.store.storehandler object at 0x7fe7bd5a4548>
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.emu.emuprofilehandler object at 0x7fe7bd5a4688>
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.cmd.cmdshellhandler object at 0x7fe7bd5a4708>
[11062025 22:15:17] ihandlers /dionaea/ihandlers.py:53-info: Starting <dionaea.tftp.tftpdownloadhandler object at 0x7fe7bd5a4788>
[11062025 22:15:17] modules /code/src/modules.c:184-message: start module 0x5632a8b19f10
[11062025 22:15:17] dionaea /code/src/dionaea.c:774-info: Installing signal handlers
[11062025 22:15:17] dionaea /code/src/dionaea.c:811-message: Creating 8 threads in pool
[11062025 22:15:17] dionaea /code/src/dionaea.c:825-debug: looping
[11062025 22:16:37] log /code/src/signals.c:36-warning: sigterm_cb loop 0x7fe7c88e88e0 w 0x5632a91906b0 revents 1024
[11062025 22:16:37] dionaea /code/src/dionaea.c:831-debug: Closing thread pool (8 active threads, 0 jobs in queue), be patient
[11062025 22:16:37] dionaea /code/src/dionaea.c:835-debug: modules free
[11062025 22:16:37] modules /code/src/modules.c:210-message: free module lib/dionaea/curl.so 0x5632a8b17670 fn 0x7fe7c6c65bb8
[11062025 22:16:37] curl /code/modules/curl/module.c:661-debug: curl_freex
[11062025 22:16:37] modules /code/src/modules.c:210-message: free module lib/dionaea/python.so 0x5632a8b191c0 fn 0x7fe7c18b83e4
[11062025 22:16:37] python /code/modules/python/module.c:258-debug: freepy /code/modules/python/module.c
[11062025 22:16:37] python /code/modules/python/module.c:270-info: stop dionaea.log 0x5632a8b0e7b0 0x7fe7c0636ae8
